# Generated by Django 3.0.5 on 2020-05-03 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200503_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='writeup',
        ),
    ]
