# Generated by Django 3.0.5 on 2020-05-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200503_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(blank=True, choices=[('D', 'Deep Learning'), ('M', 'Machine Learning')], max_length=1),
        ),
    ]
