# Generated by Django 3.0.5 on 2020-05-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_userprofileinfo_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
