# Generated by Django 3.0.5 on 2020-05-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_userprofileinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
