# Generated by Django 3.1.1 on 2020-09-23 02:59

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200923_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=martor.models.MartorField(),
        ),
    ]
