# Generated by Django 3.1.1 on 2020-09-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200923_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='old',
            field=models.BooleanField(default=False),
        ),
    ]
