# Generated by Django 3.1.1 on 2020-09-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200925_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_tag',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
